alias reload!='. ~/.zshrc'
alias rake='noglob rake'
alias npmw='npm run-script watch'
alias npmt='npm test'
alias npmtw='npm run-script test-watch'
alias npms='npm start'
alias mongodfts='mongod --setParameter textSearchEnabled=true'
alias mongodd='mongod --config /usr/local/etc/mongod.conf'
alias subl='open -a "Sublime Text"'
